# YAML Linter Configuration for Home Assistant
# This file configures yamllint for Home Assistant YAML files

extends: default

rules:
  line-length:
    max: 120
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    min-spaces-from-content: 1
  document-start: disable

ignore: |
  .git/
  .vscode/
  .storage/
  tts/
  www/community/
  custom_components/
  esphome/
  image/
