substitutions:
  name: esphome-web-1a820a
  friendly_name: hot_tub_thermometer

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point (AP)
  ssid: "Your_SSID"          # Replace with your WiFi network name (SSID)
  password: "Your_Password"   # Replace with your WiFi password

  ap:
    ssid: "ESPHotTubAP"       # WiFi AP name when device is not connected
    password: "YourAPPassword" # Password for the WiFi AP

  # Set static IP or let it be dynamically assigned by the router
  manual_ip:
    static_ip: 192.168.68.150  # Replace with your desired static IP address
    gateway: 192.168.68.1      # Replace with your router’s gateway IP
    subnet: 255.255.255.0

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

# OneWire bus configuration
one_wire:
  pin: GPIO4  # Set this to the pin where your Dallas sensor is connected

# Dallas temperature sensor
sensor:
  - platform: dallas
    name: "Hot Tub Temperature"
    update_interval: 120s
    resolution: 12
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"

# Custom configuration for temperature readings
  - platform: template
    name: "Livingroom Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class:
