esphome:
  name: esp
  friendly_name: esp

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "II2H+vFiLOHbFCgHg3XkHMLPb9IYJmwRzc0cY7GFdk0="

ota:
  - platform: esphome
    password: "2d1d91982b919910ce4dccc3d02a43f1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Fallback Hotspot"
    password: "pQ7TsO4TLSDQ"

captive_portal:
    