substitutions:
  name: esp32-bluetooth-proxy-cd26c8
  friendly_name: Bluetooth Proxy cd26c8

# Load the Bluetooth proxy package
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

# Enable API for communication with Home Assistant
api:
  encryption:
    key: eOCY7FCUZyyJGtIOaTAyT3xJF7PGnhRkN7golVQ/lcs=

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging (optional, useful for debugging)
logger:

# Over-the-Air (OTA) updates for easy firmware updates
ota:

# Bluetooth Proxy feature for Home Assistant integration
bluetooth_proxy:
