esphome:
  name: esphome
  friendly_name: ESPHome

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ChvY8OD0ybMWZxmVgEkoHGZ0LYq/LE7crl0vnMnY2TU="

ota:
  - platform: esphome
    password: "e0f83791bb5823101d701f07706bec1a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # << ADD THIS BLOCK for STATIC IP >>
  manual_ip:
    static_ip: 192.168.1.42
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    # Optional: specify DNS servers
    dns1: 8.8.8.8
    dns2: 1.1.1.1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome Fallback Hotspot"
    password: "xZRjbi4b8eyV"

captive_portal:
