substitutions:
  name: esp32-s3-box-3-641368
  friendly_name: ESP32 S3 Box 3 641368
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: QHAnb2L8XlhSR5WoKKh+NswuyoIrdSivTgOPE0LIbsI=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
